#! /usr/bin/env python3

'''
The main entry for all tasks.
'''

import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Main entry for multiple functions.")

    subparsers = parser.add_subparsers(dest="command", required=True)

    from pysrc.tasks import task_adv_rl
    task_adv_rl.build_parser(subparsers)

    from pysrc.tasks import task_gen_rl_vampire
    task_gen_rl_vampire.build_parser(subparsers)
    
    from pysrc.tasks import task_syn_gen_examples
    task_syn_gen_examples.build_parser(subparsers)

    # Parse arguments
    args = parser.parse_args()
    
    # Call the function associated with the chosen command
    args.func(args)